### ISSUE TITLE
Failed workflows block other workflows from running

### ISSUE THREAD

**Issue by ianwow** [aws-solutions/content-analysis-on-aws#3]
Failed workflows can get stuck in a "Started" state. This causes the concurrent execution queue to fill up with failed workflows that look like they're "Started" but are actually failed. You can see their real status if you look at their state machine in AWS Step Functions.

To clear the concurrent execution queue, open the content-analysisWorkflowExecution table in DynamoDB and remove one or more of the records for assets which are stuck in a Started status, like this:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/54998167/88206646-71891980-cc03-11ea-9deb-2a437c7fc454.png"><img width="364" alt="image" src="https://user-images.githubusercontent.com/54998167/88206672-7ea60880-cc03-11ea-8c74-3f7df7cc5941.png">

**Comment by markotitel** [comment]
@ianwow could you add s screenshot of StepFunctions, so that I could get a better view which will help me to quickly get to the code pieces.
I am interested in working on this issue.

**Comment by ianwow** [comment]
> @ianwow could you add s screenshot of StepFunctions, so that I could get a better view which will help me to quickly get to the code pieces.
> I am interested in working on this issue.

There are some screenshots of StepFunctions here:
https://docs.aws.amazon.com/solutions/latest/aws-content-analysis/appendix-c-state-machines.html

Thanks for checking out this issue!

**Comment by markotitel** [comment]
@ianwow I have deployed the solution and am aware of stepfunctions.
Could you screenshot where it broke for you?
