### ISSUE TITLE
Cognito - Google signon does not work

### ISSUE THREAD

**Issue by sknadella87** [aws-solutions/content-analysis-on-aws#71]
**Describe the bug**

Successfully created the stack and I can access the cloudfront Url without any issues.

Followed the instructions (listed below) to integrate the cloudfront url with google authentication via AWS cognito. After creating the user pool within cognito and setting up the google project within the developer account. The hosted UI within AWS cognito redirected me to the google page and the URL redirects with the cloudfront url + the token but prompts me for username and password.

https://aws.amazon.com/premiumsupport/knowledge-center/cognito-google-social-identity-provider/

**To Reproduce**

1. Click on create stack - https://github.com/aws-solutions/content-analysis-on-aws
2. Once the stack gets created successfully then output tab within the stack provides cloudfront URL and also creates a cognito user pool. 
3. Follow the instructions listed in https://aws.amazon.com/premiumsupport/knowledge-center/cognito-google-social-identity-provider/ URL to configure google OAuth.
4. After cognito google auth is complete the hosted UI will be available within cognito - app client settings.
5. Click on hosted UI and then you'll be redirect to google auth but after selecting your gmail the page gets redirected to cloudfront landing page instead of creating the user account and logging in directly to the website.

FYI - Tried deploying this stack in different regions numerous times and I still see the same issue. I believe the application is not storing the access and token ID or something which is not letting the website to authentication. 

**Expected behavior**
After google authentication AWS content analysis page redirects to the login page instead of using google / gmail credentials to log directly into the AWS content analysis page

**Please complete the following information about the solution:**
- Version 1.0.0 (deployed)
- Tried Version 2.0.0 deployment and the build failed.

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Comment by raulmlamzn** [comment]
Starting on August 30, 2023 Content Analysis on AWS will no longer be supported and the GitHub repository will be archived. Existing deployments will continue to run. If you have deployed Content Analysis on AWS via cloning GitHub open source code, you may continue to use the solution.

The functionality provided by Content Analysis on AWS will be superseded with functionality in Media2Cloud on AWS and Content Localization on AWS. We encourage you to explore these solutions. 

https://github.com/aws-solutions/media2cloud-on-aws
https://github.com/aws-solutions/content-localization-on-aws
