### ISSUE TITLE
UnreservedConcurrentExecution

### ISSUE THREAD

**Issue by ccontipe** [aws-solutions/content-analysis-on-aws#73]
When I tried to create the stack, I got the following message on **Event Pane** at AWS Cloudformation:

"Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]. (Service: Lambda, Status Code: 400, Request ID: 4976c838-b25a-4cbd-b669-3419f135b49d)" (RequestToken: 1a392659-ca8d-b5dc-ec6e-461411f81d06, HandlerErrorCode: InvalidRequest)"

and the stack is rollbacked, then. 

**To Reproduce**
Launch the stack, as indicated on Read.me

- [x] Region: [N.Virginia. us-east-1]
- [ ] Was the solution modified from the version published on this repository? No changes were made to the stack.

**Comment by raulmlamzn** [comment]
Starting on August 30, 2023 Content Analysis on AWS will no longer be supported and the GitHub repository will be archived. Existing deployments will continue to run. If you have deployed Content Analysis on AWS via cloning GitHub open source code, you may continue to use the solution.

The functionality provided by Content Analysis on AWS will be superseded with functionality in Media2Cloud on AWS and Content Localization on AWS. We encourage you to explore these solutions. 

https://github.com/aws-solutions/media2cloud-on-aws
https://github.com/aws-solutions/content-localization-on-aws
