### ISSUE TITLE
Bounding Boxes do not line up on images correctly

### ISSUE THREAD

**Issue by mwl387** [aws-solutions/content-analysis-on-aws#75]
**Describe the bug**
I have ingested an image (not a video) into my running solution.  Analysis is run through Rekognition.  But when I try to find the objects that Rekognition has bounding boxes for (e.g. labels with '*'), the bounding boxes do not line up with the picture.

I've tried this on multiple browsers and multiple OS's with the same result.  If I zoom my browser (200%+), then the boxes align with the image.

**To Reproduce**
- Ingest an image
- After ingestion, click on 'Analyze'
- Under 'ML Vision' and 'Objects', select a label that has an asterisk with it
- The bounding box should show up, but it will not be correctly aligned with the image

**Expected behavior**
Bounding boxes appear on top of the detected object.

**Please complete the following information about the solution:**
- [ v2.0.0 ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ us-east-1 ] Region: [e.g. us-east-1]
- [ N ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ N ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

I used this image and saw the behavior:  https://d1.awsstatic.com/aws-key-pages/homepage-key-pages/Coca-Cola.df943d34f24c3b17d8299855add943413d426de3.jpg

**Additional context**

**Comment by mwl387** [comment]
Further experimentation, it looks like it's related to the width of my browser.  If I'm at max width, then the boxes are off.  But if I reduce the width, then the boxes start showing up correctly.

**Comment by raulmlamzn** [comment]
Thank you for your suggestion. We've carefully considered your feedback and have decided not to include this feature in a future release.
