### ISSUE TITLE
CREATE_FAILED - WorkflowSchedulerLambda failed to create

### ISSUE THREAD

**Issue by mzraghib** [aws-solutions/content-analysis-on-aws#77]
Using the Cloudformation templates provided (for either US East or US West regions)  - a CREATE_FAILED error occurs with the status reason below( I replaced some text with 12345) : 

"""Embedded stack arn:aws:cloudformation:us-west-2:12345:stack/cas-MieStack-12345 was not successfully created: The following resource(s) failed to create: [WorkflowSchedulerLambda]"""

Any guidance as to how to correct this error?

**Comment by brandold** [comment]
Hi @mzraghib, try deploying using the official solutions template located here: https://aws.amazon.com/solutions/implementations/content-localization-on-aws/

We aren't actively updating the deployment links on the Github page anymore so I suspect that's the issue. I'll put an issue in our internal backlog to remove those links in the next release.

**Comment by sergeyk** [comment]
@brandold you linked to Content Localization, not Content Analysis. Did you mean to link to https://docs.aws.amazon.com/solutions/latest/content-analysis-on-aws/welcome.html?

**Comment by cassneal** [comment]
Yes please go to https://aws.amazon.com/solutions/implementations/aws-content-analysis/

**Comment by mzraghib** [comment]
unfortunately the same error comes using the template from https://aws.amazon.com/solutions/implementations/aws-content-analysis/.
