### ISSUE TITLE
Lambda Concurrent Executions Limitation on New Accounts

### ISSUE THREAD

**Issue by noah-maven-x** [aws-solutions/content-analysis-on-aws#80]
**Is your feature request related to a problem? Please describe.**
During deployment of the automated stack, on new or lightly used testing accounts, I was receiving an error in deploying the MieStack (WorkflowSchedulerLambda) as the minimum concurrent executions Service Quota set in my account was blocking it. It would be nice to list this as a common issue to smooth out deployments in the future. 

In instructions it would be helpful to list that this is automatically increased as the AWS account is used OR a Service Quota increase needs to be requested in the account to a minimum of 1,000 Applied Quota Value in the AWS account.

**Comment by cassneal** [comment]
@noah-maven-x thanks for filing this request. We have added it to our backlog for Content Localization and will look into it.

**Comment by raulmlamzn** [comment]
Starting on August 30, 2023 Content Analysis on AWS will no longer be supported and the GitHub repository will be archived. Existing deployments will continue to run. If you have deployed Content Analysis on AWS via cloning GitHub open source code, you may continue to use the solution.

The functionality provided by Content Analysis on AWS will be superseded with functionality in Media2Cloud on AWS and Content Localization on AWS. We encourage you to explore these solutions. 

https://github.com/aws-solutions/media2cloud-on-aws
https://github.com/aws-solutions/content-localization-on-aws
