### ISSUE TITLE
OpenSearch Consumer Lambda [ERROR] Runtime.ImportModuleError: cannot import name 'RequestsHttpConnection' from 'elasticsearch' 

### ISSUE THREAD

**Issue by rickosaws** [aws-solutions/content-analysis-on-aws#85]
**Describe the bug**
The OpenSearch Consumer Lambda is throwing an Import Error when invoked when using elasticsearch==8.6.0 in requirements.txt

**To Reproduce**
Have deployed from repo and rebuilt from source with the same result. 

**Expected behavior**
Consumer Lambda should execute successfully.

**Please complete the following information about the solution:**
- [aws-media-insights-engine version v5.0.0] 

- [All] Region: [e.g. us-east-1]
- [ No ] Was the solution modified from the version published on this repository?
- [ NA ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ Yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ Yes ] Were there any errors in the CloudWatch Logs?

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_handler': cannot import name 'RequestsHttpConnection' from 'elasticsearch' (/var/task/elasticsearch/__init__.py) Traceback (most recent call last): 
**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

RequestsHttpConnection looks to be deprecated in Elasticsearch 8.0+ in favour of using RequestsHttpNode from elastic_transport.

**Comment by raulmlamzn** [comment]
Starting on August 30, 2023 Content Analysis on AWS will no longer be supported and the GitHub repository will be archived. Existing deployments will continue to run. If you have deployed Content Analysis on AWS via cloning GitHub open source code, you may continue to use the solution.

The functionality provided by Content Analysis on AWS will be superseded with functionality in Media2Cloud on AWS and Content Localization on AWS. We encourage you to explore these solutions. 

https://github.com/aws-solutions/media2cloud-on-aws
https://github.com/aws-solutions/content-localization-on-aws
