### ISSUE TITLE
Analyze shows 0 results

### ISSUE THREAD

**Issue by kotowick** [aws-solutions/content-analysis-on-aws#89]
**Describe the bug**
After uploading a photo, the system is not detecting objects (or anything) in the photos.

**To Reproduce**
Deploy the latest stack and upload a photo

**Expected behavior**
An uploaded photo should have something detected in it.

**Please complete the following information about the solution:**
- [x] Version: v2.0.2

- [x] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/1714316/232330489-f1047b32-3d0f-4098-9e62-3997f07707e6.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1714316/232330515-9f0f0301-3978-45db-bc46-e1c6069beb91.png">

**Additional context**
`
{
  "ServiceToken": "arn:aws:lambda:us-east-1:XXXXXXXX:function:sponsorship-1-MieStack-1F9A-WorkflowCustomResource-kLFTnccUKcqZ",
  "ApiVersion": "3.0.0",
  "Configuration": {
    "MediainfoImage": {
      "MediaType": "Image",
      "Enabled": true
    }
  },
  "Version": "v0",
  "Next": "RekognitionStage",
  "Definition": "{\"StartAt\": \"ValidationStage\", \"States\": {\"Complete Stage ValidationStage\": {\"Type\": \"Task\", \"Resource\": \"arn:aws:lambda:us-east-1:XXXXXXXX:function:sponsorship-1-MieStack-1F9AC7C-CompleteStageLambda-kvTnsCHAIKLY\", \"End\": true}, \"ValidationStage\": {\"Type\": \"Parallel\", \"Next\": \"Complete Stage ValidationStage\", \"ResultPath\": \"$.Outputs\", \"Branches\": [{\"StartAt\": \"Filter MediainfoImage Media Type? (ValidationStage)\", \"States\": {\"Filter MediainfoImage Media Type? (ValidationStage)\": {\"Type\": \"Task\", \"Parameters\": {\"StageName.$\": \"$.Name\", \"Name\": \"MediainfoImage\", \"Input.$\": \"$.Input\", \"Configuration.$\": \"$.Configuration.MediainfoImage\", \"AssetId.$\": \"$.AssetId\", \"WorkflowExecutionId.$\": \"$.WorkflowExecutionId\", \"Type\": \"Image\", \"Status\": \"$.Status\"}, \"Resource\": \"arn:aws:lambda:us-east-1:XXXXXXXX:function:sponsorship-1-MieStack-1F9AC-FilterOperationLambda-m6czjgSfzGeV\", \"ResultPath\": \"$.Outputs\", \"OutputPath\": \"$.Outputs\", \"Next\": \"Skip MediainfoImage? (ValidationStage)\", \"Retry\": [{\"ErrorEquals\": [\"Lambda.ServiceException\", \"Lambda.AWSLambdaException\", \"Lambda.SdkClientException\", \"Lambda.Unknown\", \"MasExecutionError\"], \"IntervalSeconds\": 2, \"MaxAttempts\": 2, \"BackoffRate\": 2}], \"Catch\": [{\"ErrorEquals\": [\"States.ALL\"], \"Next\": \"MediainfoImage Failed (ValidationStage)\", \"ResultPath\": \"$.Outputs\"}]}, \"Skip MediainfoImage? (ValidationStage)\": {\"Type\": \"Choice\", \"Choices\": [{\"Variable\": \"$.Status\", \"StringEquals\": \"Started\", \"Next\": \"Execute MediainfoImage (ValidationStage)\"}], \"Default\": \"MediainfoImage Not Started (ValidationStage)\"}, \"MediainfoImage Not Started (ValidationStage)\": {\"Type\": \"Succeed\"}, \"Execute MediainfoImage (ValidationStage)\": {\"Type\": \"Task\", \"Resource\": \"arn:aws:lambda:us-east-1:XXXXXXXX:function:sponsorship-1-MieStack-1F9AC7CV61HAR-Ope-Mediainfo-6RXrQy9bqx6z\", \"ResultPath\": \"$.Outputs\", \"OutputPath\": \"$.Outputs\", \"Next\": \"Did MediainfoImage Complete (ValidationStage)\", \"Retry\": [{\"ErrorEquals\": [\"Lambda.ServiceException\", \"Lambda.AWSLambdaException\", \"Lambda.SdkClientException\", \"Lambda.Unknown\", \"MasExecutionError\"], \"IntervalSeconds\": 2, \"MaxAttempts\": 2, \"BackoffRate\": 2}], \"Catch\": [{\"ErrorEquals\": [\"States.ALL\"], \"Next\": \"MediainfoImage Failed (ValidationStage)\", \"ResultPath\": \"$.Outputs\"}]}, \"Did MediainfoImage Complete (ValidationStage)\": {\"Type\": \"Choice\", \"Choices\": [{\"Variable\": \"$.Status\", \"StringEquals\": \"Complete\", \"Next\": \"MediainfoImage Succeeded (ValidationStage)\"}], \"Default\": \"MediainfoImage Failed (ValidationStage)\"}, \"MediainfoImage Failed (ValidationStage)\": {\"Type\": \"Task\", \"End\": true, \"Resource\": \"arn:aws:lambda:us-east-1:XXXXXXXX:function:sponsorship-1-MieStack-1F9AC7-OperatorFailedLambda-uh9T2Nhcsokc\", \"ResultPath\": \"$\", \"Retry\": [{\"ErrorEquals\": [\"Lambda.ServiceException\", \"Lambda.AWSLambdaException\", \"Lambda.SdkClientException\", \"Lambda.Unknown\", \"MasExecutionError\"], \"IntervalSeconds\": 2, \"MaxAttempts\": 2, \"BackoffRate\": 2}]}, \"MediainfoImage Succeeded (ValidationStage)\": {\"Type\": \"Succeed\"}}}], \"Catch\": [{\"ErrorEquals\": [\"States.ALL\"], \"Next\": \"Complete Stage ValidationStage\", \"ResultPath\": \"$.Outputs\"}]}}}",
  "ResourceType": "STAGE",
  "Id": "9ecea691-e079-4f8f-98ea-f2f034ac2860",
  "Operations": [
    "MediainfoImage"
  ],
  "Name": "ValidationStage",
  "Created": "1681605982.393308",
  "Status": "Started",
  "Metrics": {},
  "AssetId": "06960104-e3cb-4ab8-ab33-2144a25c9728",
  "WorkflowExecutionId": "130d7b21-c8f3-47c7-ab4b-0c1c1fc36e7a",
  "MetaData": {},
  "Input": {
    "Media": {
      "Image": {
        "S3Bucket": "sponsorship-1-miestack-1f9ac7cv61har-dataplane-n2lvkmvmtt1s",
        "S3Key": "public/upload/PXL_20221231_002325716.MP (1).jpg"
      }
    },
    "MetaData": {}
  }
}
`

**Comment by eric80116** [comment]
I met the same issue. I can see all the analytics results in s3 bucket but nothing in the website.

**Comment by raulmlamzn** [comment]
We have added this bug to our backlog. However, please keep in mind this solution is deprecating and we encourage customers to use Media2Cloud or Content Localization on AWS instead per our note here [https://aws.amazon.com/solutions/implementations/content-analysis-on-aws/]

**Comment by chewycharis** [comment]
+1 on this. We are trying to use this solution. Escalation would be greatly appreciated!

**Comment by raulmlamzn** [comment]
Starting on August 30, 2023 Content Analysis on AWS will no longer be supported and the GitHub repository will be archived. Existing deployments will continue to run. If you have deployed Content Analysis on AWS via cloning GitHub open source code, you may continue to use the solution.

The functionality provided by Content Analysis on AWS will be superseded with functionality in Media2Cloud on AWS and Content Localization on AWS. We encourage you to explore these solutions. 

https://github.com/aws-solutions/media2cloud-on-aws
https://github.com/aws-solutions/content-localization-on-aws
